### PR TITLE
(DED-498) Add prefilled URL to GoogleForms feedback modal field

### PR DESCRIPTION
**Pull request by AdalbertusLiver**
# Deploy preview

- [Deploy Preview](https://63e26b4ef22033005002fafd--livechat-public-docs.netlify.app/)

# Links

Link your Jira ticket.

- [Jira](https://livechatinc.atlassian.net/browse/DED-498)

# Description

- Add prefilled URL to GoogleForms feedback modal field

# Review and release

Apply changes and resolve conflicts. Once the described functionality lands on prod, let us know on #platform-docs-releases that your PR is ready for release. We will **merge** and **publish** the changes.

### CODE REVIEW

**Review by arturfracala — APPROVED** [review]

**Comment by ale-kacperczyk** [comment]
@AdalbertusLiver, could you link the deploy preview for this?

**Comment by AdalbertusLiver** [comment]
> 

done

**Comment by AdalbertusLiver** [comment]
> @AdalbertusLiver, could you link the deploy preview for this?

done

**Review by ale-kacperczyk — APPROVED** [review]
LGTM 😊

**Pull request merged**
